<ul class="liste-buttons">
    <li class="btn-admin"><a href="<?php echo $this->url('admin/weather/locations/add'); ?>"><?php echo $this->translate('Ajouter un lieu'); ?></a></li>
</ul>

<?php $filterCriteria = ($this->filterCriteria) ? $this->filterCriteria : 'city';  ?>
<?php $filterWay = ($this->filterWay) ? $this->filterWay : 'ASC';  ?>

<h2><?php echo $this->translate('Lieux') ?></h2>
    <table id="app_codes">
        <thead>
            <tr>
                <th><?php echo $this->translate('Ville') ?>
                <?php if($filterCriteria =='city' && $filterWay == 'ASC'): ?>
            	    <a href="<?php echo $this->url('admin/weather/locations/list', array('criteria' => 'city', 'filterWay' => 'DESC')); ?>">
            	    	<img src="<?php echo $this->adminAssetPath('images/admin/arrow-down.png');?>" alt="" />
            	    </a>
    			<?php else : ?>
    				<a href="<?php echo $this->url('admin/weather/locations/list', array('criteria' => 'city', 'filterWay' => 'ASC')); ?>">
    					<img src="<?php echo $this->adminAssetPath('images/admin/arrow-up.png');?>" alt="" />
    				</a>
            	<?php endif; ?>
                </th>
                <th><?php echo $this->translate('Pays') ?>
                <?php if($filterCriteria =='country' && $filterWay == 'ASC'): ?>
            	    <a href="<?php echo $this->url('admin/weather/locations/list', array('criteria' => 'country', 'filterWay' => 'DESC')); ?>">
            	    	<img src="<?php echo $this->adminAssetPath('images/admin/arrow-down.png');?>" alt="" />
            	    </a>
    			<?php else : ?>
    				<a href="<?php echo $this->url('admin/weather/locations/list', array('criteria' => 'country', 'filterWay' => 'ASC')); ?>">
    					<img src="<?php echo $this->adminAssetPath('images/admin/arrow-up.png');?>" alt="" />
    				</a>
            	<?php endif; ?>
                </th>
                <th><?php echo $this->translate('Region') ?></th>
                <th><?php echo $this->translate('Latitude') ?></th>
                <th><?php echo $this->translate('Longitude') ?></th>
                <th></th>
                <th></th>

            </tr>
            <tr>
            <?php $this->formFilter->prepare(); ?>
            <?php echo $this->form()->openTag($formFilter); ?>
            <?php foreach($formFilter->get('columns') as $column) :?>
            <td>
                <?php echo $this->formElement($column->get('columnName')); ?>
                <?php echo $this->formElement($column->get('columnFilter')); ?>
            </td>
            <?php endforeach; ?>
            <td></td>
            <td>
                <?php echo $this->formSubmit($formFilter->get('submit')); ?>
            </td>
            <?php echo $this->form()->closeTag($formFilter); ?>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->locations as $location):?>
            <tr>
                <td><?php echo $location->getCity(); ?></td>
                <td><?php echo $location->getCountry(); ?></td>
                <td><?php echo $location->getRegion(); ?></td>
                <td><?php echo $location->getLatitude(); ?></td>
                <td><?php echo $location->getLongitude(); ?></td>
                <td></td>
                <?php $deleteLink = $this->url('admin/weather/locations/remove', array('locationId' => $location->getId()));?>
                <td><a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Supprimer'); ?></a></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>

<?php echo (count($this->locations)>1)?$this->paginationControl($this->locations, 'Sliding', 'playground-weather/location/pagination_locations.phtml', array('criteria' => $filterCriteria, 'way' => $filterWay)):''; ?>

<ul class="liste-buttons">
    <li class="btn-admin"><a href="<?php echo $this->url('admin/weather/locations/add'); ?>"><?php echo $this->translate('Ajouter un lieu'); ?></a></li>
</ul>

