<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundweather');// Pour le texte ?>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>

<h2><?php echo $this->translate('Add a map image'); ?></h2>
<?php echo $this->form()->openTag($form) ?>

    <?php echo $this->formButton($form->get('submit')); ?>

    <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('description')); ?>
        <?php echo $this->formInput($form->get('description')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('country')); ?>
        <?php echo $this->formSelect($form->get('country')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('image')); ?>
        <?php echo $this->formFile($form->get('image')); ?>
    </div>
        <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formHidden($form->get('imageWidth')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formHidden($form->get('imageHeight')); ?>
    </div>
    <?php if($form->get('imageURL')->getValue() != ''):?>
        <img src="<?php echo $this->basePath($form->get('imageURL')->getValue()); ?>" />
    <?php endif;?>
    <p><?php echo $this->translate('Top Left')?></p>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('latitude1')); ?>
        <?php echo $this->formInput($form->get('latitude1')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('longitude1')); ?>
        <?php echo $this->formInput($form->get('longitude1')); ?>
    </div>
    <p style="clear:both;"><?php echo $this->translate('Bottom Right')?></p>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('latitude2')); ?>
        <?php echo $this->formInput($form->get('latitude2')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('longitude2')); ?>
        <?php echo $this->formInput($form->get('longitude2')); ?>
    </div>
    <h3 style="clear:both;"><?php echo $this->translate('Add locations for which you want to display weather on this map')?></h3>
    <div class="label-input" id="locations">
        <?php echo $this->formMultiCheckbox($form->get('locationsCheckboxes')); ?>
    </div>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        var updateForm = function() {
            var country = $('#country').val();
            var checkboxes = $('#locations').children("label");
            $.each(checkboxes, function(key, obj) {
            	if($(obj)[0]['innerText'].match(country)) {
            		$(obj).show();
            	}
            	else {
            		$(obj).hide();
            	}
            });
        }

        updateForm();
        $('#country').change(function() {
            updateForm();
        });


    });
</script>