<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundweather');// Pour le texte ?>
    <?php
    $form = $this->form;
    $form->prepare();
    ?>

<h2><?php echo $this->translate('Add a map image'); ?></h2>
<?php echo $this->form()->openTag($form) ?>

    <?php echo $this->formButton($form->get('submit')); ?>

    <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('description')); ?>
        <?php echo $this->formInput($form->get('description')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('country')); ?>
        <?php echo $this->formSelect($form->get('country')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formLabel($form->get('image')); ?>
        <?php echo $this->formFile($form->get('image')); ?>
    </div>
        <div class="label-input">
        <?php echo $this->formHidden($form->get('id')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formHidden($form->get('imageWidth')); ?>
    </div>
    <div class="label-input">
        <?php echo $this->formHidden($form->get('imageHeight')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('ptX1')); ?>
        <?php echo $this->formInput($form->get('ptX1')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('ptY1')); ?>
        <?php echo $this->formInput($form->get('ptY1')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('latitude1')); ?>
        <?php echo $this->formInput($form->get('latitude1')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('longitude1')); ?>
        <?php echo $this->formInput($form->get('longitude1')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('ptX2')); ?>
        <?php echo $this->formInput($form->get('ptX2')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('ptY2')); ?>
        <?php echo $this->formInput($form->get('ptY2')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('latitude2')); ?>
        <?php echo $this->formInput($form->get('latitude2')); ?>
    </div>
    <div class="label-input" style="float:left;">
        <?php echo $this->formLabel($form->get('longitude2')); ?>
        <?php echo $this->formInput($form->get('longitude2')); ?>
    </div>
    <?php if($form->get('imageURL')->getValue() != ''):?>
        <img src="<?php echo $this->basePath($form->get('imageURL')->getValue()); ?>" />
    <?php endif;?>

    <div class="label-input" style="clear:left; float:right;">
        <?php echo $this->formLabel($form->get('bottomRightLatitude')); ?>
        <?php echo $this->formInput($form->get('bottomRightLatitude')); ?>
    </div>
    <div class="label-input" style="float:right;">
        <?php echo $this->formLabel($form->get('bottomRightLongitude')); ?>
        <?php echo $this->formInput($form->get('bottomRightLongitude')); ?>
    </div>
    <canvas id="map-image" width="" height="">

    </canvas>

<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
  var c = document.getElementById("map-image");
  var ctx = c.getContext("2d");
</script>