<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundweather');// Pour le texte ?>
<div class="weather-table-widget">
    <?php $today = current($data); ?>
    <h5><?php echo $this->translate('Weather in '); ?><span><?php echo $today->getLocation()->getCity(); ?></span></h5>
    <span><?php echo $today->getLocation()->getCountry(); ?> - <?php echo $today->getLocation()->getLatitude(); ?> - <?php echo $today->getLocation()->getlongitude(); ?></span>
    <table cellpadding="0" cellspacing="0">
        <tbody>
            <?php foreach($data as $day) : ?>
            <tr class="day-weather-item">
                <td class="weekday"><?php echo $day->getDate(); ?></td>
                <td class="min-temp"><?php echo $day->getMinTemperature(); ?></td>
                <td class="max-temp"><?php echo $day->getMaxTemperature(); ?></td>
<!--                 <td class="symbol"> -->
                    <img src="<?php //echo $this->frontendAssetPath($day->getWeatherCode()->getIconURL();?>" alt="Très nuageux ou alternance d’éclaircies et de nuages" />
<!--                 </td> -->
                <?php foreach($day->times as $time) : ?>
                    <td class="time">
                        <div><?php echo $time->getTime(); ?></div>
                        <div><?php echo $time->getTemperature(); ?></div>
                        <div><?php echo $time->getWeatherCode(); ?></div>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>