<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundweather');// Pour le texte ?>
<?php $locale= $this->plugin('translate')->getTranslator()->getLocale(); ?>
<div class="weather-table-widget">
    <?php $location = $this->data['location']; ?>
    <h5><?php echo $this->translate('Weather in '); ?><span><?php echo $location->getCity(); ?></span> (<?php echo $location->getCountry(); ?>)</h5>
    <span><?php echo $this->translate('Latitude') . ' : ' . $location->getLatitude(); ?> - <?php echo $this->translate('Longitude') . ' : ' . $location->getLongitude(); ?></span>
    <table cellpadding="0" cellspacing="0">
        <tbody>
            <?php foreach($data['days'] as $day) : ?>
            <tr class="day-weather-item">
                <td class="weekday"><?php echo $this->dateFormat($day['date'], IntlDateFormatter::LONG, IntlDateFormatter::NONE, $locale); ?></td>
                <td class="min-temp"><?php echo $day['minTemperature']; ?></td>
                <td class="max-temp"><?php echo $day['maxTemperature']; ?></td>
                <td class="symbol">
                    <?php $code = $day['weatherCode']; ?>
                    <span><?php echo $code['code']; ?> | <?php echo $code['description']; ?></span>
                    <img src="<?php echo '../' . $code['iconURL']; ?>" alt="<?php echo $code['description']; ?>" />
                </td>
                <?php foreach($day['times'] as $time) : ?>
                    <td class="time">
                        <div><?php echo $this->dateFormat($time['time'], IntlDateFormatter::NONE, IntlDateFormatter::SHORT, $locale); ?></div>
                        <div><?php echo $time['temperature']; ?></div>
                    </td>
                    <td class="symbol">
                        <?php $code = $time['weatherCode']; ?>
                        <span><?php echo $code['code']; ?> | <?php echo $code['description']; ?></span>
                        <img src="<?php echo '../' . $code['iconURL']; ?>" alt="<?php echo $code['description']; ?>" />
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>